version: '3'
services:
  test-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off